"""
database.py — Database initialization and write functions
Hybrid Network Monitoring Agent (SNMP + ICMP)

Key fix vs. original:
  Alert deduplication — the original write_alert() inserted a new row on
  every poll cycle that crossed a threshold. With a 30s interval, a single
  sustained high-CPU condition would flood the alerts table with hundreds of
  identical rows per hour. The fixed write_alert() checks whether an
  unresolved alert of the same type already exists for that host before
  inserting a new one, preventing alert storms.
"""

import sqlite3
import datetime

DB_PATH = "network_monitor.db"


def init_db() -> None:
    """Create all tables if they do not already exist."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # SNMP polling results
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS snmp_metrics (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp   TEXT    NOT NULL,
            host_ip     TEXT    NOT NULL,
            cpu_pct     REAL,
            mem_pct     REAL,
            if_in_mbps  REAL,
            if_out_mbps REAL,
            if_errors   INTEGER,
            sys_uptime  TEXT,
            reachable   INTEGER NOT NULL DEFAULT 1
        )
    """)

    # ICMP probe results
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS icmp_metrics (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp       TEXT    NOT NULL,
            host_ip         TEXT    NOT NULL,
            avg_rtt_ms      REAL,
            min_rtt_ms      REAL,
            max_rtt_ms      REAL,
            packet_loss_pct REAL    NOT NULL,
            jitter_ms       REAL,
            status          TEXT    NOT NULL
        )
    """)

    # Alerts generated by threshold breaches
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp       TEXT    NOT NULL,
            host_ip         TEXT    NOT NULL,
            alert_type      TEXT    NOT NULL,
            severity        TEXT    NOT NULL,
            metric_value    REAL,
            threshold_value REAL,
            message         TEXT,
            resolved        INTEGER NOT NULL DEFAULT 0
        )
    """)

    conn.commit()
    conn.close()
    print("[DB] Database initialised successfully.")


def write_snmp(host_ip: str, cpu_pct, mem_pct, if_in_mbps, if_out_mbps,
               if_errors, sys_uptime, reachable: int = 1) -> None:
    ts = datetime.datetime.utcnow().isoformat()
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        INSERT INTO snmp_metrics
            (timestamp, host_ip, cpu_pct, mem_pct, if_in_mbps,
             if_out_mbps, if_errors, sys_uptime, reachable)
        VALUES (?,?,?,?,?,?,?,?,?)
    """, (ts, host_ip, cpu_pct, mem_pct, if_in_mbps,
          if_out_mbps, if_errors, sys_uptime, reachable))
    conn.commit()
    conn.close()


def write_icmp(host_ip: str, avg_rtt, min_rtt, max_rtt,
               packet_loss: float, jitter, status: str) -> None:
    ts = datetime.datetime.utcnow().isoformat()
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        INSERT INTO icmp_metrics
            (timestamp, host_ip, avg_rtt_ms, min_rtt_ms, max_rtt_ms,
             packet_loss_pct, jitter_ms, status)
        VALUES (?,?,?,?,?,?,?,?)
    """, (ts, host_ip, avg_rtt, min_rtt, max_rtt,
          packet_loss, jitter, status))
    conn.commit()
    conn.close()


def write_alert(host_ip: str, alert_type: str, severity: str,
                metric_value: float, threshold_value: float,
                message: str) -> None:
    """
    Insert an alert only if there is no existing UNRESOLVED alert of the
    same type for this host. This prevents a single sustained condition
    (e.g. high CPU) from flooding the alerts table on every poll cycle.

    An alert remains "active" (resolved=0) until manually marked resolved
    via resolve_alert(). The metric_value is updated on the existing row
    so the dashboard always shows the latest reading.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # Check for an existing unresolved alert of the same type on this host
    cursor.execute("""
        SELECT id FROM alerts
        WHERE host_ip = ? AND alert_type = ? AND resolved = 0
        LIMIT 1
    """, (host_ip, alert_type))
    existing = cursor.fetchone()

    if existing:
        # Update the metric value and message on the existing alert so the
        # dashboard reflects the latest reading without creating a new row.
        cursor.execute("""
            UPDATE alerts
            SET metric_value = ?, message = ?, timestamp = ?
            WHERE id = ?
        """, (metric_value, message, datetime.datetime.utcnow().isoformat(),
              existing[0]))
    else:
        # No existing open alert — create a fresh one
        ts = datetime.datetime.utcnow().isoformat()
        cursor.execute("""
            INSERT INTO alerts
                (timestamp, host_ip, alert_type, severity,
                 metric_value, threshold_value, message)
            VALUES (?,?,?,?,?,?,?)
        """, (ts, host_ip, alert_type, severity,
              metric_value, threshold_value, message))

    conn.commit()
    conn.close()


def resolve_alert(host_ip: str, alert_type: str) -> None:
    """
    Mark all open alerts of a given type for a host as resolved.
    Call this when the metric drops back below its threshold.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        UPDATE alerts
        SET resolved = 1
        WHERE host_ip = ? AND alert_type = ? AND resolved = 0
    """, (host_ip, alert_type))
    conn.commit()
    conn.close()
