"""
database.py — Database initialization and write functions
Hybrid Network Monitoring Agent (SNMP + ICMP)
"""

import sqlite3
import datetime

DB_PATH = "network_monitor.db"


def init_db():
    """Create all tables if they do not already exist."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # SNMP polling results
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS snmp_metrics (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp   TEXT    NOT NULL,
            host_ip     TEXT    NOT NULL,
            cpu_pct     REAL,
            mem_pct     REAL,
            if_in_mbps  REAL,
            if_out_mbps REAL,
            if_errors   INTEGER,
            sys_uptime  TEXT,
            reachable   INTEGER NOT NULL DEFAULT 1
        )
    """)

    # ICMP probe results
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS icmp_metrics (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp       TEXT    NOT NULL,
            host_ip         TEXT    NOT NULL,
            avg_rtt_ms      REAL,
            min_rtt_ms      REAL,
            max_rtt_ms      REAL,
            packet_loss_pct REAL    NOT NULL,
            jitter_ms       REAL,
            status          TEXT    NOT NULL
        )
    """)

    # Alerts generated by threshold breaches
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp       TEXT    NOT NULL,
            host_ip         TEXT    NOT NULL,
            alert_type      TEXT    NOT NULL,
            severity        TEXT    NOT NULL,
            metric_value    REAL,
            threshold_value REAL,
            message         TEXT,
            resolved        INTEGER NOT NULL DEFAULT 0
        )
    """)

    conn.commit()
    conn.close()
    print("[DB] Database initialised successfully.")


def write_snmp(host_ip, cpu_pct, mem_pct, if_in_mbps, if_out_mbps,
               if_errors, sys_uptime, reachable=1):
    ts = datetime.datetime.utcnow().isoformat()
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        INSERT INTO snmp_metrics
            (timestamp, host_ip, cpu_pct, mem_pct, if_in_mbps,
             if_out_mbps, if_errors, sys_uptime, reachable)
        VALUES (?,?,?,?,?,?,?,?,?)
    """, (ts, host_ip, cpu_pct, mem_pct, if_in_mbps,
          if_out_mbps, if_errors, sys_uptime, reachable))
    conn.commit()
    conn.close()


def write_icmp(host_ip, avg_rtt, min_rtt, max_rtt,
               packet_loss, jitter, status):
    ts = datetime.datetime.utcnow().isoformat()
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        INSERT INTO icmp_metrics
            (timestamp, host_ip, avg_rtt_ms, min_rtt_ms, max_rtt_ms,
             packet_loss_pct, jitter_ms, status)
        VALUES (?,?,?,?,?,?,?,?)
    """, (ts, host_ip, avg_rtt, min_rtt, max_rtt,
          packet_loss, jitter, status))
    conn.commit()
    conn.close()


def write_alert(host_ip, alert_type, severity, metric_value,
                threshold_value, message):
    ts = datetime.datetime.utcnow().isoformat()
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        INSERT INTO alerts
            (timestamp, host_ip, alert_type, severity,
             metric_value, threshold_value, message)
        VALUES (?,?,?,?,?,?,?)
    """, (ts, host_ip, alert_type, severity,
          metric_value, threshold_value, message))
    conn.commit()
    conn.close()
